#!/bin/bash

if [ -f "./.autorelease/test-testpypi" ]; then
    source ./.autorelease/test-testpypi || exit 1
elif [ -n "$AUTORELEASE_TEST_TESTPYPI" ]; then
    eval $AUTORELEASE_TEST_TESTPYPI || exit 1
else
    python -m pip install pytest
    python -c "import $PACKAGE_IMPORT_NAME" || exit 1
    py.test --pyargs $PACKAGE_IMPORT_NAME  || exit 1
fi

