language: python
python:
  - '3.6'
  - '2.7'
  - '3.4'
  - '3.5'

branches:
  only:
  - master
  - stable

env:
  global:
    - CANONICAL_PYTHON="3.6"
    - CODECLIMATE=""
    - TWINE_USERNAME="dwhswenson"
    # TWINE_PASSWORD
    - secure: "wp+7rQ11ipJ2r/Yde8AWuZcBVgrPQPOnJdddntFgKSXh5aI3xiZm7mgHyy+mGg5mf8smErF0SwpZ6U4b2VQiXfS8XDwie+/gOrpFNkAPY0jHLRegSK1oXvqBTgZHQI3zeD4Q+qUFDVOIpu70JC+UrM5nEUC3jXo/T2ojJ7AdW7JROfgptewaFWLEaa38KHPZYUGjD9NGiB+49k220xEVdKtRK1cnogcCpxnPBsXiACz9VhYQ5f+r0wHSVDH151eUyiqdXiDjWTJ6o6uyaxm4jbECdFhfX0qoirp4l26Rf1UDk0HJYG+hEvT1IG/fThH6WhubXTpLMpUIdaPgZYvjhZcrpyJymtPMQ6RhrHifJh90nBWaN+vzeBdFwxav9skQypf3uS94XynynOOSTuZKCHwHBzlKypuB3RxSUIrZu9xnrJMkOD5jtLo6fsDhlZeNSy9zzKFZA+LoLPiQaZKpA8W8gUR31PcIo1VDiClGpu54Xu8Nm0agjExlQkBPa9xZNik7yNv381Gm0NLCwnwQtnZXY/V9CNRXUmATAMzoBcLf6xgZxHroQPBYB2mw76e7UB2fzRWYaby8T39GU3C8vczxaqSHDam2qwKieruzNSaRHLOGDQcx7N8WM/f8GtKcXxpPwxdjv0r8sAZ6YoIlbYVcQfpXAOPQD9Gz5vn+JKI="

before_install:
  - echo "before install"

install:
  - pip install -r requirements.txt
  - pip install -e .
  - pip install -r devtools/pip-install/full_testing.txt
  - pip list

script:
  - python -c "import autorelease"
  - python release_check.py --branch ${TRAVIS_BRANCH}

after_success:
  - echo "success!"

jobs:
  include:
    - stage: deploy testpypi
      if: "(branch = master) and (type = pull_request)"
      python: '3.6'
      install: skip
      script: 
        - python setup.py sdist bdist_wheel
        - twine upload --repository-url https://test.pypi.org/legacy/ dist/*
    - stage: test testpypi
      if: "(branch = master) and (type = pull_request)"
      python: '3.6'
      install:
        - pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple autorelease
      script:
        - cd ~
        - python -c "import autorelease"
        - echo "py.test --pyargs autorelease"  # if I had py.test stuff
    - stage: cut release
      if: "(branch = stable) and (not type in (pull_request, cron))"
      python: '3.6'
      install: skip
      script:
        - echo "make_github_release"
    - stage: deploy pypi
      if: tag =~ ^v[0-9]+\.
      deploy:
        provider: pypi
        distributions: sdist bdist_wheel
        user: dwhswenson
        password:
          secure: "VnOfkKXPAGeUfWBQra+WISnmgQV1yiz1ZsOExSqzDvdnOkGZ3ToLYiNn0sEpPgzeeYOx8nkjWUYZ8e8b5oYmU1fQ+5AXJ/b8L5T463IMj0Qe4PL4leCfv9Rqn90NywUwGaYQseeOi8c1yB8XaMqWkBmwjFuHmk0B7PQ5DISWJa9NR9/ydGc5Rp8H0/z40eVkaNksNHZjEfr9FHMt1PFM3KWecH6WkGscSVii+B/dfAcDWOW/UKI1094ckQkGNxtOEOMR6NkiLqFgb6iCOUTfyypELRNHLb2mB5d+6/doy93uJbY9dgFgI0glUrr0Ira/Nn3KGObxezvl5noe9+quD10r4KTl338qINR6H/NGL/t62TDG+hXn7xpGJ9i6UjJt5xmZio22neo0UEchSSvERsAkgChYQJ4N2jA2WVVUKuH+REjDEARjWrhx1u8gMB4vQGjI+47nxEvRiSl/ICwLqHswLK2Y+uqdsDdKZZq5kLxgcIqeNxuUzNj2fAGSlEbZVJEMrEe01hVC44OSiz2mQ8ndaP/Nf6i/n+SHgE+oeIJasHbgyNHpfR36RFR5QsVKu0lKyQjjVsm7HtMzz+JnSfO1hfDK8n94AYjDyEP9T/4Hrwo4KAGKLER9rokyC3psrTWNiefYB1ODYJneTC6Uhyh9Sq/+RlNEtPdN8YjGQAE="
