version: ~> 1.0

language: python
python:
  - '3.8'
  - '3.7'
  - '3.6'
  - '2.7'

branches:
  only:
  - master
  - stable
  - /^v\d+(\.\d+)+$/

env:
  global:
    - AUTORELEASE_TEST_TESTPYPI="cd ~ &&  python -c 'import autorelease'"
    - TWINE_USERNAME="dwhswenson"
    # TWINE_PASSWORD
    - secure: "wp+7rQ11ipJ2r/Yde8AWuZcBVgrPQPOnJdddntFgKSXh5aI3xiZm7mgHyy+mGg5mf8smErF0SwpZ6U4b2VQiXfS8XDwie+/gOrpFNkAPY0jHLRegSK1oXvqBTgZHQI3zeD4Q+qUFDVOIpu70JC+UrM5nEUC3jXo/T2ojJ7AdW7JROfgptewaFWLEaa38KHPZYUGjD9NGiB+49k220xEVdKtRK1cnogcCpxnPBsXiACz9VhYQ5f+r0wHSVDH151eUyiqdXiDjWTJ6o6uyaxm4jbECdFhfX0qoirp4l26Rf1UDk0HJYG+hEvT1IG/fThH6WhubXTpLMpUIdaPgZYvjhZcrpyJymtPMQ6RhrHifJh90nBWaN+vzeBdFwxav9skQypf3uS94XynynOOSTuZKCHwHBzlKypuB3RxSUIrZu9xnrJMkOD5jtLo6fsDhlZeNSy9zzKFZA+LoLPiQaZKpA8W8gUR31PcIo1VDiClGpu54Xu8Nm0agjExlQkBPa9xZNik7yNv381Gm0NLCwnwQtnZXY/V9CNRXUmATAMzoBcLf6xgZxHroQPBYB2mw76e7UB2fzRWYaby8T39GU3C8vczxaqSHDam2qwKieruzNSaRHLOGDQcx7N8WM/f8GtKcXxpPwxdjv0r8sAZ6YoIlbYVcQfpXAOPQD9Gz5vn+JKI="
    # AUTORELEASE_TOKEN
    - secure: "g0qz8XRM8eiI20K9i7r//E1U6gSZ3MgyBzUYBRtez2C+HwNuKoIQCtX2f33vXQBvfySiKvF0jolp1GIlze5FvH1h3/+G+3BoX/9L/qFl/mioXKxGbczW4J/iD3tt0VjVXs++1MxKtHq9TOZB92sGDy5GG0IBSTS12NDlqFS9QPcRPrgH2DOMzpj8rT1aHGWxsDfR5BKtUv7rkstLK9SghsYhhITYtBPIiKuvsIXOtGziNAMA5i7ohcMQSpCYF7I8DzfSPeibnlN0rdAwKSHubNfHxTSALSnhum6PAj8UkiF1up08wDiazr8iWu/XJZ+l6xCB4ElP/2eiP4db4/rExrbvifhcmNA67nVbVO4D/AIz5GShRxmYdgWdy4LwZfuY/HZUyNIYhRFRf0iu5cbotAiQqeydRqr3O7xVrmxmn+WOEqTvm+13Crlno1J1PpAhLEbJL8tJQDK4JSYOEujAwh/b0Iqc1/QCz1WzAIEDEdjnxfSm1Bl+YpgCQyo7i0xGtQoTk3wG53Tz4H5RV2oHvR37D3mKZX6G/3Vm9gHUcgfwryJbAKEgQJXZ4bzgxrK7Y6rNJ/hY9liRT/om/ubenpvJ0VFntTjdrm85+YJMT67V852x0OG2CITp5AOaJNVQ1289My6fj3cbfjYBp1/w990WhAtCu5BNIak3s+eSm2w="

before_install:
  - git fetch --tags

install:
  - pip install -r requirements.txt
  - pip install -e .
  - pip install -r devtools/pip-install/full_testing.txt
  - pip list

script:
  - python -c "import autorelease"
  - autorelease-release -h
  - python release_check.py --branch ${TRAVIS_BRANCH} --event ${TRAVIS_EVENT_TYPE}

after_success:
  - echo "success!"

import: autorelease-local.yml
