# AUTORELEASE v0.4.0
# for nonrelease, use @main
# for release, use v${VERSION}, e.g., v1.0.0
stages:
    - test
    - deploy testpypi
    - test testpypi
    - cut release
    - deploy pypi

import:
    - dwhswenson/autorelease:travis_stages/deploy_testpypi.yml@main
    - dwhswenson/autorelease:travis_stages/test_testpypi.yml@main
    - dwhswenson/autorelease:travis_stages/cut_release.yml@main
    - dwhswenson/autorelease:travis_stages/deploy_pypi.yml@main
