# AUTORELEASE v0.2.1.dev0
# for nonrelease, use @master
# for release, use v${VERSION}, e.g., v1.0.0
import:
    - dwhswenson/autorelease:travis_stages/deploy_testpypi.yml@master
    - dwhswenson/autorelease:travis_stages/cut_release.yml@master
    - dwhswenson/autorelease:travis_stages/deploy_pypi.yml@master
    - dwhswenson/autorelease:travis_stages/test_testpypi.yml@master

stages:
    - test
    - deploy_testpypi
    - test_testpypi
    - deploy_pypi
    - cut_release
