stages:
  - test
  - deploy_testpypi
  - test_testpypi
  - cut_release
  - deploy_pypi

import:
  - travis_stages/deploy_testpypi.yml
  - travis_stages/test_testpypi.yml
  - travis_stages/cut_release.yml
  - travis_stages/deploy_pypi.yml
