stages:
  - test
  - deploy testpypi
  - test testpypi
  - cut release
  - deploy pypi

import:
  - travis_stages/deploy_testpypi.yml
  - travis_stages/test_testpypi.yml
  - travis_stages/cut_release.yml
  - travis_stages/deploy_pypi.yml
