jobs:
  include:
    - stage: deploy testpypi
      # This stage runs when you make a PR to stable. It tests that the
      # deployment to testpypi works.
      if: "(branch = stable) and (type = pull_request)"
      install:
        - pip install twine #autorelease
        - hash -r
      script: 
        #- bump-dev-version  # comes from autorelease
        - python setup.py --version
        - python setup.py sdist bdist_wheel
        - twine upload --repository-url https://test.pypi.org/legacy/ dist/*
