jobs:
  include:
    - stage: test testpypi
      # This stage run when you make a PR to stable; after the package has
      # been deployed to testpypi. It checks that the deployed package
      # works.
      if: "(branch = stable) and (type = pull_request)"
      before_install: skip
      install:
        - pip install autorelease
        #- pip install git+https://github.com/dwhswenson/autorelease@ops_fixes
        # this is for debugging anything in autorelease used here (change
        # the branch tag to whatever is needed)
        #- pip install git+https://github.com/dwhswenson/autorelease.git@release-0.0.18#egg=autorelease
        - hash -r
        - wait-for-testpypi
        - export PROJECT=`python setup.py --name`
        - export VERSION=`pypi-max-version $PROJECT`
        - echo "Installing ${PROJECT}==${VERSION} (allowing pre-releases)"
        - pip install --pre --force-reinstall --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple ${PROJECT}==${VERSION}
      before_script: skip
      script: |
          if [ -n "$AUTORELEASE_TEST_TESTPYPI" ]; then
            eval $AUTORELEASE_TEST_TESTPYPI
          else
            if [ -z "$PACKAGE_IMPORT_NAME" ]; then
              PACKAGE_IMPORT_NAME=$PROJECT
            fi
            cd ~
            python -c "import $PACKAGE_IMPORT_NAME"
            py.test --pyargs $PACKAGE_IMPORT_NAME
          fi
      after_failure: skip
      after_success: skip
      after_script: skip
