jobs:
  include:
    - stage: test testpypi
      # This stage run when you make a PR to stable; after the package has
      # been deployed to testpypi. It checks that the deployed package
      # works.
      if: "(branch = stable) and (type = pull_request)"
      install:
        #- pip install autorelease
        # this is for debugging autorelease itself
        - pip install git+https://github.com/dwhswenson/autorelease.git@release-0.0.18#egg=autorelease
        - hash -r
        #- wait-for-testpypi setup.py
        - export PROJECT=`python setup.py --name`
        - export VERSION=`bump-dev-version --get-max`
        - echo "Installing ${PROJECT}==${VERSION} (allowing pre-releases)"
        - pip install --pre --force-reinstall --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple ${PROJECT}==${VERSION}
      script: |
          if [ -n "$AUTORELEASE_TEST_TESTPYPI" ]; then
            eval $AUTORELEASE_TEST_TESTPYPI
          else
            cd ~
            python -c "import $PROJECT"
            py.test --pyargs $PROJECT
          fi
