stages:
  - stage: cut_release
    displayName: Cut Release
    jobs:
      - job: cut_release
        displayName: Cut release
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.8'
          - bash: python -m pip install autorelease
            displayName: "Install autorelease"
          - bash: |
              VERSION=`python setup.py --version`
              PROJECT=`python setup.py --name`
              echo $PROJECT $VERSION
              echo "This is where we cut the release"
              #autorelease-release --project $PROJECT --version $VERSION --token $AUTORELEASE_TOKEN
            env:
              AUTORELEASE_TOKEN: $(AUTORELEASE_TOKEN)
            displayName: Cut release
