package:
  name: autorelease
  # add ".dev0" for unreleased versions
  version: "0.2.2"

source:
  path: ../../

build:
  preserve_egg_dir: True
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - packaging
    - pyyaml
    - gitpython
    - python-dateutil
    - requests
    - future

test:
  requires:
    - pytest
    #- pytest-cov
    #- python-coveralls

  source_files:
    - autorelease/tests/*

  imports:
    - autorelease

  commands:
    - py.test -vv

about:
  home: https://github.com/dwhswenson/autorelease
  license: MIT
  summary: "Check the version and branches in release cycle"
