package:
  name: autorelease
  # add ".dev0" for unreleased versions
  version: "0.0.11.dev0"

source:
  path: ../../

build:
  preserve_egg_dir: True
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - packaging
    - pyyaml
    - gitpython==2.1.7
    - requests==2.18
    - future==0.16

test:
  requires:
    - pytest
    #- pytest-cov
    #- python-coveralls

  source_files:
    - autorelease/tests/*

  imports:
    - autorelease

  commands:
    - py.test -vv

about:
  home: https://github.com/dwhswenson/autorelease
  license: LGPL-2.1 or later
  summary: "Check the version and branches in release cycle"
