# Vendored from Autorelease $VERSION
# Update by updating Autorelease and running `autorelease vendor actions`
name: "Autorelease Deploy"
on:
  release:
    types: [published]

jobs:
  deploy_pypi:
    if: $${{ github.repository == '$GITHUB_REPO' }}
    runs-on: ubuntu-latest
    name: "Deploy to PyPI"
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - run: |
          python -m pip install twine wheel build
        name: "Install release tools"
      - run: |
          python -m build --sdist --wheel
          twine check dist/*
        name: "Build and check package"
      - uses: pypa/gh-action-pypi-publish@release/v1
        name: "Deploy to pypi"
 
