name: "Autorelease"
on:
  pull_request:
    branches:
      - stable

defaults:
  run:
    shell: bash

jobs:
  deploy_testpypi:
    runs-on: ubuntu-latest
    name: "Deployment test"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - run: |  # TODO: move this to an action
          source ./.github/workflows/autorelease-default-env.sh
          cat autorelease-env.sh >> $GITHUB_ENV
          eval $INSTALL_AUTORELEASE
        name: "Install autorelease"
      - run: |
          deploy-pypi --repository-url https://test.pypi.org/legacy/
        env:
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
        name: "Deploy to testpypi"
  test_testpypi:
    runs-on: ubuntu-latest
    name: "Autorelease: Test deployed"
    needs: deploy_testpypi
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - run: |  # TODO: move this to an action
          source ./.github/workflows/autorelease-default-env.sh
          cat autorelease-env.sh >> $GITHUB_ENV
          eval $INSTALL_AUTORELEASE
        name: "Install autorelease"
      - run: test-testpypi

