name: Autorelease
on:
  release:
    types: [published]

jobs:
  deploy_pypi:
    runs-on: ubuntu-latest
    name: "Deploy to PyPI"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - run: |  # TODO: move this to an action
          source ./.github/workflows/autorelease-default-env.sh
          cat ./.github/workflows/autorelease-env.sh >> $GITHUB_ENV
          eval $INSTALL_AUTORELEASE
        name: "Install autorelease"
      - run:
          deploy-pypi
        name: "Deploy to PyPI"
        env:
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
