name: "Unit tests"
on:
  pull_request:
    branches:
      - main
      - stable
  push:
    branches:
      - main
    tags:
      - "v*"
  schedule:
    - cron: "25 5 * * *"

defaults:
  run:
    shell: bash

jobs:
  test_suite:
    runs-on: ubuntu-latest
    name: "Tests"
    strategy:
      matrix:
        CONDA_PY:
          - "3.13"
          - "3.12"
          - "3.11"
          - "3.10"
          - "3.9"
          - "3.8"
           
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.CONDA_PY }}
      - name: "Installation"
        run: |
          python -m pip install -r requirements.txt
          python -m pip install -r devtools/pip-install/full_testing.txt
          python -m pip install -e .
      - name: "Versions"
        run: pip list
      - name: "Tests"
        env:
          PR_BRANCH: ${{ github.event.pull_request.base.ref }}
          REF: ${{ github.ref }}
          EVENT: ${{ github.event_name }}
          #EVENT_INFO: ${{ toJson(github.event) }}  # useful debug
        run: |
          if [ "$EVENT" != "pull_request" ]; then
            BRANCH=$REF
          else
            BRANCH=$PR_BRANCH
          fi
          echo "Generic: $GITHUB_REF"
          echo "PUSH_REF: $PUSH_REF"
          echo "EVENT: $EVENT"
          echo "BRANCH: $BRANCH"
          python -c "import autorelease"
          autorelease-release -h
          python release_check.py
          autorelease check
